export default [
    {
      id: 1,
      title: "Web developer",
      spots: 3,
      duration: 1,
      company: {
        name: "Ooredoo",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/O/ooredoo-logo-DC5A203B79-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
    {
      id: 2,
      title: "Network engineer",
      spots: 3,
      duration: 3,
      company: {
        name: "Mobilis",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/M/mobilis-logo-005D3C94BA-seeklogo.com.png",
        address: "centre ville, Constantine",
        offers: 3,
      },
    },
    {
      id: 3,
      title: "Web developer",
      spots: 3,
      duration: 1,
      company: {
        name: "Ooredoo",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/O/ooredoo-logo-DC5A203B79-seeklogo.com.png",
        address: "El Khroub, Constantine",
        offers: 3,
      },
    },
    {
      id: 4,
      title: "Network engineer",
      spots: 3,
      duration: 3,
      company: {
        name: "Mobilis",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/M/mobilis-logo-005D3C94BA-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
    {
      id: 5,
      title: "Web developer",
      spots: 3,
      duration: 1,
      company: {
        name: "Ooredoo",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/O/ooredoo-logo-DC5A203B79-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
    { 
      id: 6,
      title: "Network engineer",
      spots: 3,
      duration: 3,
      company: {
        name: "Mobilis",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/M/mobilis-logo-005D3C94BA-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
    {
      id: 7,
      title: "Web developer",
      spots: 3,
      duration: 1,
      company: {
        name: "Ooredoo",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/O/ooredoo-logo-DC5A203B79-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
    {
      id: 8,
      title: "Network engineer",
      spots: 3,
      duration: 3,
      company: {
        name: "Mobilis",
        domain: "Telecommunications",
        logo: "https://seeklogo.com/images/M/mobilis-logo-005D3C94BA-seeklogo.com.png",
        address: "Ali Mendjli, Constantine",
        offers: 3,
      },
    },
  ]
